### ISSUE TITLE
omero.server.datadir

### ISSUE THREAD

**Issue by kennethgillen** [ome/ansible-role-omero-server#28]
I notice my server deploys using this role have stopped having `omero.data.dir` set in the run of the playbooks, which was a var I was providing to this role.

Though I had set `omero_server_datadir_manage` to false, I was still setting that variable to define my own datadir.

I read now in the role readme:

"omero_server_datadir_manage: Initialise of modify the top level of OMERO data directories, deafult True, if False no data directories will be created or modified, and the omero.data.dir configuration parameter will not be set"

I'm going to set this in my own playbook, but it's worth considering whether this role should still set that value if it's defined.

Was the `omero.data.dir` not being set a change? I only noticed this during my last server deployment.

**Comment by manics** [comment]
`omero_server_datadir_manage` is an unstable/developer feature https://github.com/openmicroscopy/ansible-role-omero-server/tree/2.0.3#unstable-features

What happens if it's left as the default `True`?
