### ISSUE TITLE
checkupgrade task fails

### ISSUE THREAD

**Issue by juliomateoslangerak** [ome/ansible-role-omero-server#42]
Hi,
The installation fails at this point:
TASK [ome.omero_server : omero server | checkupgrade] **************************
fatal: [default]: FAILED! => {"msg": "template error while templating string: no filter named 'version_compare'. String: {{ omero_server_symlink_st.stat.exists and (omero_server_version.stdout | version_compare( _omero_server_new_version, omero_server_checkupgrade_comparator)) }}"}

It is a first intallation. I don't know if that matters

**Comment by manics** [comment]
Which version of ansible are you using?

**Comment by juliomateoslangerak** [comment]
Hi,
I just saw a bit too late some comment about version 2.6.XX to be more tested. I had 2.9.XX. I downgraded my ansible to 2.7.10 (the lowest I have in Fedora 30) and it is working now.

**Comment by manics** [comment]
> In 2.5 version_compare was renamed to version
https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#version-comparison

The old name must've been removed in 2.9. If you re-open this issue we could fix it for the next major release.

**Comment by juliomateoslangerak** [comment]
OK
