### ISSUE TITLE
`flush_handlers` task does not support when conditional

### ISSUE THREAD

**Issue by paddyroddy** [ome/ansible-role-omero-server#63]
Not sure what is causing this warning as no `when` is used to my knowledge
https://github.com/ome/ansible-role-omero-server/blob/f87ded09d57c01d60f456750722f51aa5e6a8c88/tasks/omero-systemd.yml#L16-L17
<img width="527" alt="image" src="https://user-images.githubusercontent.com/15052188/173385609-799566c2-aabe-4db1-afa9-0f09a650ea88.png">

**Comment by sbesson** [comment]
I think it comes from the fact that the playbook is conditionally executed in https://github.com/ome/ansible-role-omero-server/blob/f87ded09d57c01d60f456750722f51aa5e6a8c88/tasks/main.yml#L13-L14

There is a fairly long upstream issue about this behavior  and the confusion it creates - https://github.com/ansible/ansible/issues/41313 although it looks like there is no plan for a resolution.

**Comment by paddyroddy** [comment]
> I think it comes from the fact that the playbook is conditionally executed in
> 
> https://github.com/ome/ansible-role-omero-server/blob/f87ded09d57c01d60f456750722f51aa5e6a8c88/tasks/main.yml#L13-L14
> 
> There is a fairly long upstream issue about this behavior and the confusion it creates - [ansible/ansible#41313](https://github.com/ansible/ansible/issues/41313) although it looks like there is no plan for a resolution.

Ah thanks, didn't think to look a level up. Will have a look
